### ISSUE TITLE
Windows 10 Driver for Pixel kit

### ISSUE THREAD

**Issue by netmanchris** [KanoComputing/community-sdk#8]
Trying to connect Pixel kit to Window 10 machine. Device Manager shows the Pixel kit as FT231X USB UART for which there are no drivers available.  Doing a little digging, it appears I should be installign drivers for the Ftdi chip from here. 
https://www.ftdichip.com/Drivers/VCP.htm

Can anyone confirm if this is accurate or if there's another method I should be using for loading the drivers?
[update]  I was able to successfully install the drivers above and Windows 10 now sees the device as a "USB Serial Converter" 

thanks!

**Comment by murilopolese** [comment]
Have you tried to install Kano Code as described on [before you start requirements](https://github.com/KanoComputing/community-sdk/wiki/Installation-Guides#before-you-start-requirements)?

**Comment by netmanchris** [comment]
Ouch. Is my face red?  ( I think we can close this for now )

**Comment by murilopolese** [comment]
Don't be ashamed, @netmanchris! It's a silly step that can be skipped if you are willing to install the FTDI drivers yourself. I just added there because teachers and beginners (and myself most of the times) tend to have difficulties installing drivers and Kano Code does it automagically :D 

Feel free to close the issue or add any more questions.

**Comment by murilopolese** [comment]
Hey @netmanchris, do you believe this issue is solved? :)

**Comment by netmanchris** [comment]
Yes - Sorry!  closing now.
